---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurants
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: restaurants
  template:
    metadata:
      labels:
        app: restaurants
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: restaurants
      containers:
        - name: restaurants
          image: ghcr.io/goodfood-cesi/api-restaurants:latest
          ports:
            - containerPort: 80
          env:
            - name: DB_DRIVER
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DB_DRIVER
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DB_PORT
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DB_DATABASE
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DB_PASSWORD
            - name: RECAPTCHA_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: RECAPTCHA_SECRET_KEY
            - name: MJ_APIKEY_PUBLIC
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: MJ_APIKEY_PUBLIC
            - name: MJ_APIKEY_PRIVATE
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: MJ_APIKEY_PRIVATE
      imagePullSecrets:
        - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: restaurants-svc
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: restaurants
