version: '3'
services:
  goodfood:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${APP_PORT:-8000}:80'
    volumes:
      - '.:/app'
    networks:
      - goodfood
    depends_on:
      - mysql
  mysql:
    image: 'mysql:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
    volumes:
      - 'goodfood-mysql:/var/lib/mysql'
    networks:
      - goodfood
networks:
  goodfood:
    driver: bridge
volumes:
  goodfood-mysql:
    driver: local
